version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${POSTGRES_JDBC_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - .env

    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d

volumes:
  db-data:
